services:
  prepare_data:
    build:
      context: .
      dockerfile: data_prepare/Dockerfile.prepare_data
    ports:
      - "8001:8001"
    volumes:
      - shared_data:/shared/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - shared_data:/shared/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    depends_on:
      - prepare_data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  shared_data: